// packages/vod-h5-demo/src/components/slider-item/index.tsx
import React, { PropsWithChildren, useState, MouseEvent, useMemo, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { Viewer } from '@volcengine/imagex-react';
import LikeIcon from '@/assets/svg/like.svg?react';
import LikeActiveIcon from '@/assets/svg/like-active.svg?react';
import FavIcon from '@/assets/svg/fav.svg?react';
import FavActiveIcon from '@/assets/svg/fav-active.svg?react';
import DIcon from '@/assets/svg/d.svg?react';

import { IVideoDataWithModel } from '@/typings';

import style from './index.module.less';

interface ISliderItemProps extends PropsWithChildren {
  isActive: boolean;
  activeIndex: number;
  data: IVideoDataWithModel;
  index: number;
  isRecommend?: boolean;
  getCurrentTime: () => number;
  playNextStatus: string;
}

const imageSizes = [600, 750, 800, 960];

const mockFavLikeData = () => (Math.random() * 50 + 50).toFixed(1);

const SliderItem: React.FC<ISliderItemProps> = ({
  activeIndex,
  data,
  index,
  isRecommend,
  getCurrentTime,
  children,
}) => {
  const coverUrl = data?.videoModel?.PosterUrl ?? data?.coverUrl;
  const episodeDesc = data?.episodeDetail?.episodeDesc;
  const dramaTitle = data?.episodeDetail?.dramaInfo?.dramaTitle;
  const totalEpisodeNumber = data?.episodeDetail?.dramaInfo?.totalEpisodeNumber;
  const episodeNumber = data?.episodeDetail?.episodeNumber;
  const [isLike, setIsLike] = useState<boolean>(false);
  const [isFav, setIsFav] = useState<boolean>(false);

  const navigate = useNavigate();
  const bottomText = `观看完整短剧 · 全${totalEpisodeNumber}集`;

  const favNum = mockFavLikeData();
  const likeNum = mockFavLikeData();

  const onBottomBtnClick = useCallback(
    (e: MouseEvent) => {
      e.stopPropagation();
      const dramaId = data?.episodeDetail?.dramaInfo?.dramaId;
      const startTime = getCurrentTime();
      if (dramaId) {
        navigate(`/playlet/theater/?id=${dramaId}&startTime=${startTime}`);
      }
    },
    [data?.episodeDetail?.dramaInfo?.dramaId, getCurrentTime, navigate],
  );

  // 距离当前两集加载，减少dom数目
  const shouldRenderContent = useMemo(() => Math.abs(activeIndex - index) <= 2, [activeIndex, index]);
  return (
    <div className={style.wrapper}>
      {shouldRenderContent && (
        <>
          <div className={`${style.poster}`}>
            <Viewer
              layout="raw"
              placeholder="skeleton"
              objectFit="cover"
              objectPosition="center"
              loading="eager"
              src={coverUrl}
              imageSizes={imageSizes}
              loader={({ src, format, width }) => {
                const path = src.split('/');
                const finalPath = path.splice(1).join('/');
                return `${__IMAGEX_DOMAIN__}/${finalPath}~${__IMAGEX_TEMPLATE__}:${width}:q75.${format}`;
              }}
            />
          </div>
          <div id={`swiper-video-container-${index}`} className={style.videoContainer}>
            <div className="veplayer-cus-gradient-wrapper" />
            {children}
          </div>
          <div className={style.right} onClick={e => e.stopPropagation()}>
            <div
              className={style.btnItem}
              onClick={e => {
                e.stopPropagation();
                setIsLike(!isLike);
                return false;
              }}
            >
              {isLike ? <LikeActiveIcon className={style.icon} /> : <LikeIcon className={style.icon} />}
              <div className={style.num}>{`${likeNum}w`}</div>
            </div>
            <div
              className={style.btnItem}
              onClick={e => {
                e.stopPropagation();
                setIsFav(!isFav);
              }}
            >
              {isFav ? <FavActiveIcon className={style.icon} /> : <FavIcon className={style.icon} />}
              <div className={style.num}>{`${favNum}w`}</div>
            </div>
          </div>
          <div className={style.bottom} onClick={e => e.stopPropagation()}>
            <div className={style.title}>{dramaTitle}</div>
            <div className={style.des}>
              {isRecommend && episodeNumber ? (
                <>
                  {`第${episodeNumber}集`}
                  <span className={style.split} />
                  {episodeDesc}
                </>
              ) : (
                episodeDesc
              )}
            </div>
            {isRecommend && (
              <div className={style.info}>
                <div className={style.text}>
                  <DIcon className={style.icon} />
                  <div>{bottomText}</div>
                </div>
                <div onClick={onBottomBtnClick} className={style.btn}>
                  连续看
                </div>
              </div>
            )}
          </div>
        </>
      )}
    </div>
  );
};

export default SliderItem;

// packages/vod-h5-vue-demo/src/components/SliderItem.vue
<template>
  <div class="wrapper">
    <template v-if="shouldRenderContent">
      <div class="poster">
        <img v-if="coverUrl" :src="coverUrl" alt="poster" />
      </div>
      <div :id="`swiper-video-container-${index}`" class="video-container">
        <div class="veplayer-cus-gradient-wrapper" />
        <slot />
      </div>
      <div class="right" @click="stopPropagation">
        <div class="btn-item" @click="toggleLike">
          <LikeActiveIcon v-if="isLike" class="icon" />
          <LikeIcon v-else class="icon" />
          <div class="num">{{ likeNum }}w</div>
        </div>
        <div class="btn-item" @click="toggleFav">
          <FavActiveIcon v-if="isFav" class="icon" />
          <FavIcon v-else class="icon" />
          <div class="num">{{ favNum }}w</div>
        </div>
      </div>
      <div class="bottom" @click="stopPropagation">
        <div class="title">
          {{ dramaTitle }}
        </div>
        <div class="des">
          <template v-if="isRecommend && episodeNumber">
            {{ `第${episodeNumber}集` }}
            <span class="split" />
            {{ episodeDesc }}
          </template>
          <template v-else>
            {{ episodeDesc }}
          </template>
        </div>
        <div v-if="isRecommend" class="info">
          <div class="text">
            <DIcon class="icon" />
            <div>{{ bottomText }}</div>
          </div>
          <div class="btn" @click="onBottomBtnClick">连续看</div>
        </div>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
/**
 * Copyright 2024 (c) Beijing Volcano Engine Technology Co., Ltd.
 * SPDX-License-Identifier: MIT
 */
import { computed, ref, onBeforeMount } from 'vue';
import { useRouter } from 'vue-router';
import type { IVideoDataWithModel } from '@/typings';

import LikeIcon from '@/assets/svg/like.svg';
import LikeActiveIcon from '@/assets/svg/like-active.svg';
import FavIcon from '@/assets/svg/fav.svg';
import FavActiveIcon from '@/assets/svg/fav-active.svg';
import DIcon from '@/assets/svg/d.svg';

const props = defineProps({
  data: {
    type: Object as () => IVideoDataWithModel,
    required: true,
  },
  index: {
    type: Number,
    required: true,
  },
  isActive: {
    type: Boolean,
    default: false,
  },
  activeIndex: {
    type: Number,
    required: true,
  },
  isRecommend: {
    type: Boolean,
    default: false,
  },
  playNextStatus: {
    type: String,
    default: '',
  },
  getCurrentTime: {
    type: Function,
    default: () => 0,
  },
});

const router = useRouter();
const isLike = ref(false);
const isFav = ref(false);
const favNum = ref('0');
const likeNum = ref('0');

// 模拟点赞收藏数据
const mockFavLikeData = () => Math.floor(Math.random() * 5000 + 5000).toString();

// 属性
const coverUrl = props.data?.videoModel?.PosterUrl ?? props.data?.coverUrl;
const episodeDesc = props.data?.episodeDetail?.episodeDesc;
const dramaTitle = props.data?.episodeDetail?.dramaInfo?.dramaTitle;
const totalEpisodeNumber = props.data?.episodeDetail?.dramaInfo?.totalEpisodeNumber;
const episodeNumber = props.data?.episodeDetail?.episodeNumber;
const bottomText = computed(() => `观看完整短剧 · 全${totalEpisodeNumber}集`);

// 是否需要渲染内容（距离当前显示项两个项内才渲染）
const shouldRenderContent = computed(() => Math.abs(props.activeIndex - props.index) <= 2);

// 方法
const stopPropagation = (e: Event) => {
  e.stopPropagation();
};

const toggleLike = (e: Event) => {
  e.stopPropagation();
  isLike.value = !isLike.value;
};

const toggleFav = (e: Event) => {
  e.stopPropagation();
  isFav.value = !isFav.value;
};

const onBottomBtnClick = (e: Event) => {
  e.stopPropagation();
  const dramaId = props.data?.episodeDetail?.dramaInfo?.dramaId;
  const startTime = props.getCurrentTime();
  if (dramaId) {
    router.push(`/playlet/theater/?id=${dramaId}&startTime=${startTime}`);
  }
};

onBeforeMount(() => {
  favNum.value = mockFavLikeData();
  likeNum.value = mockFavLikeData();
});
</script>

<style scoped lang="less">
.wrapper {
  position: relative;
  width: 100%;
  height: 100%;
  font-family:
    'PingFang SC',
    PingFang SC,
    Helvetica Neue,
    Helvetica,
    STHeiTi,
    Microsoft YaHei,
    WenQuanYi Micro Hei,
    sans-serif;
  transform: translate3d(0, 0, 0);

  .poster {
    width: 100%;
    height: 100%;
    position: relative;
    display: flex;
    justify-content: center;
    align-items: center;
    transform: translate3d(0, 0, 0);

    img {
      height: auto;
      width: 100%;
    }
  }

  .video-container {
    position: absolute;
    top: 0;
    bottom: 0;
    width: 100%;
    height: 100%;
    opacity: 1;
  }

  :deep(.veplayer-cus-gradient-wrapper) {
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 280px;
    background: linear-gradient(180deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.34) 97.36%);
    pointer-events: none;
    mix-blend-mode: normal;
    z-index: 1;
    transform: translate3d(0, 0, 0);
  }

  .right {
    position: absolute;
    right: calc(14px + env(safe-area-inset-right));
    bottom: 10px;
    z-index: 2;
    display: flex;
    flex-direction: column;
    justify-content: center;
    transform: translate3d(0, 0, 0);

    .btn-item {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      margin-bottom: 14px;
      color: #fff;
      text-align: center;
      cursor: pointer;

      .icon {
        width: 36px;
        height: 36px;
      }

      .num {
        font-size: 13px;
        font-style: normal;
        font-weight: 400;
        line-height: normal;
        color: #fff;
        text-align: center;
        text-shadow:
          0 0 4px rgb(0 0 0 / 20%),
          0 1px 1px rgb(0 0 0 / 15%);
      }
    }
  }

  .bottom {
    position: absolute;
    z-index: 2;
    right: 70px;
    bottom: 12px;
    left: calc(12px + env(safe-area-inset-left));
    transform: translate3d(0, 0, 0);
    text-align: justify;

    .title {
      margin-bottom: 5px;
      font-size: 17px;
      font-style: normal;
      font-weight: 500;
      line-height: normal;
      color: #fff;
      user-select: none;
      font-family:
        'PingFang SC',
        PingFang SC,
        Helvetica Neue,
        Helvetica,
        STHeiTi,
        Microsoft YaHei,
        WenQuanYi Micro Hei,
        sans-serif;
    }

    .des {
      width: 100%;
      margin-bottom: 12px;
      font-size: 15px;
      font-style: normal;
      font-weight: 400;
      line-height: normal;
      color: #fff;
      user-select: none;

      .split {
        display: inline-block;
        width: 1px;
        height: 13px;
        background-color: rgba(255, 255, 255, 0.5);
        box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.3);
        margin: 0 8px;
        vertical-align: middle;
      }
    }

    .info {
      position: relative;
      display: flex;
      align-items: center;
      justify-content: space-between;
      height: 48px;
      padding: 0 12px;
      line-height: 48px;
      background: rgb(41 41 41 / 34%);
      border-radius: 8px;

      .text {
        position: relative;
        width: fit-content;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 13px;
        font-style: normal;
        font-weight: 500;
        line-height: 48px;
        color: #fff;
        text-align: left;
        font-family:
          'PingFang SC',
          PingFang SC,
          Helvetica Neue,
          Helvetica,
          STHeiTi,
          Microsoft YaHei,
          WenQuanYi Micro Hei,
          sans-serif;

        .icon {
          width: 12px;
          height: 12px;
          margin-right: 7px;
        }
      }

      .btn {
        height: 28px;
        padding: 0 12px;
        margin: 10px 0 10px 18px;
        font-size: 12px;
        font-weight: 600;
        line-height: 28px;
        color: #fff;
        text-align: center;
        text-shadow: 0 1px 1px rgb(0 0 0 / 15%);
        background: rgb(255 255 255 / 15%);
        backdrop-filter: blur(17px);
        border-radius: 6px;
        cursor: pointer;
      }
    }
  }
}
</style>
